"""dew

Revision ID: 1f6f19a27244
Revises: 3b0ee71bff1d
Create Date: 2023-09-05 14:19:28.485107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f6f19a27244'
down_revision: Union[str, None] = '3b0ee71bff1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('solvedee', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'solvedee')
    # ### end Alembic commands ###
