"""add nioktr5

Revision ID: 2af72b63ce06
Revises: 4b11b72803a0
Create Date: 2023-09-18 13:04:13.549052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2af72b63ce06'
down_revision: Union[str, None] = '4b11b72803a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budget_type', 'funds')
    op.drop_column('budget_type', 'kbk')
    op.drop_constraint('nioktr_organization_type_id_fkey', 'nioktr', type_='foreignkey')
    op.drop_column('nioktr', 'organization_type_id')
    op.add_column('nioktr_budget', sa.Column('funds', sa.Integer(), nullable=False))
    op.add_column('nioktr_budget', sa.Column('kbk', sa.String(), nullable=False))
    op.add_column('nioktr_budget', sa.Column('budget_type_id', sa.Integer(), nullable=False))
    op.add_column('nioktr_budget', sa.Column('nioktr_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'nioktr_budget', 'nioktr', ['nioktr_id'], ['id'])
    op.create_foreign_key(None, 'nioktr_budget', 'budget_type', ['budget_type_id'], ['id'])
    op.add_column('nioktr_critical_tech', sa.Column('nioktr_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'nioktr_critical_tech', 'nioktr', ['nioktr_id'], ['id'])
    op.add_column('nioktr_priority_directions', sa.Column('nioktr_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'nioktr_priority_directions', 'nioktr', ['nioktr_id'], ['id'])
    op.add_column('nioktr_types', sa.Column('nioktr_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'nioktr_types', 'nioktr', ['nioktr_id'], ['id'])
    op.add_column('organization', sa.Column('organization_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'organization', 'organization_type', ['organization_type_id'], ['id'])
    op.add_column('subject', sa.Column('subject_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'subject', 'subject_type', ['subject_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subject', type_='foreignkey')
    op.drop_column('subject', 'subject_type_id')
    op.drop_constraint(None, 'organization', type_='foreignkey')
    op.drop_column('organization', 'organization_type_id')
    op.drop_constraint(None, 'nioktr_types', type_='foreignkey')
    op.drop_column('nioktr_types', 'nioktr_id')
    op.drop_constraint(None, 'nioktr_priority_directions', type_='foreignkey')
    op.drop_column('nioktr_priority_directions', 'nioktr_id')
    op.drop_constraint(None, 'nioktr_critical_tech', type_='foreignkey')
    op.drop_column('nioktr_critical_tech', 'nioktr_id')
    op.drop_constraint(None, 'nioktr_budget', type_='foreignkey')
    op.drop_constraint(None, 'nioktr_budget', type_='foreignkey')
    op.drop_column('nioktr_budget', 'nioktr_id')
    op.drop_column('nioktr_budget', 'budget_type_id')
    op.drop_column('nioktr_budget', 'kbk')
    op.drop_column('nioktr_budget', 'funds')
    op.add_column('nioktr', sa.Column('organization_type_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('nioktr_organization_type_id_fkey', 'nioktr', 'organization_type', ['organization_type_id'], ['id'])
    op.add_column('budget_type', sa.Column('kbk', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('budget_type', sa.Column('funds', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
