"""add nioktr

Revision ID: 7fe1e6e8af80
Revises: 1f6f19a27244
Create Date: 2023-09-18 10:48:35.133655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fe1e6e8af80'
down_revision: Union[str, None] = '1f6f19a27244'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('funds', sa.Integer(), nullable=False),
    sa.Column('kbk', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nioktr_budget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nioktr_critical_tech',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nioktr_priority_directions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nioktr_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('subject_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('nioktr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rosrid_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('annotation', sa.String(), nullable=True),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('document_date', sa.Date(), nullable=False),
    sa.Column('work_start_date', sa.Date(), nullable=False),
    sa.Column('work_end_date', sa.Date(), nullable=False),
    sa.Column('contract_number', sa.String(), nullable=True),
    sa.Column('work_supervisor_id', sa.Integer(), nullable=False),
    sa.Column('organization_supervisor_id', sa.Integer(), nullable=False),
    sa.Column('organization_executor_id', sa.Integer(), nullable=False),
    sa.Column('organization_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_executor_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['organization_supervisor_id'], ['author.id'], ),
    sa.ForeignKeyConstraint(['organization_type_id'], ['organization_type.id'], ),
    sa.ForeignKeyConstraint(['work_supervisor_id'], ['author.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keywords_nioktr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nioktr_id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keyword.id'], ),
    sa.ForeignKeyConstraint(['nioktr_id'], ['nioktr.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('organization', sa.Column('ogrn', sa.Integer(), nullable=True))
    op.add_column('organization', sa.Column('inn', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization', 'inn')
    op.drop_column('organization', 'ogrn')
    op.drop_table('keywords_nioktr')
    op.drop_table('nioktr')
    op.drop_table('subject_type')
    op.drop_table('organization_type')
    op.drop_table('nioktr_types')
    op.drop_table('nioktr_priority_directions')
    op.drop_table('nioktr_critical_tech')
    op.drop_table('nioktr_budget')
    op.drop_table('budget_type')
    # ### end Alembic commands ###
