"""add nioktr3

Revision ID: e26eab340243
Revises: ff9b28ef9c3d
Create Date: 2023-09-18 11:40:07.524052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e26eab340243'
down_revision: Union[str, None] = 'ff9b28ef9c3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nioktr', sa.Column('type_id', sa.Integer(), nullable=False))
    op.drop_constraint('nioktr_organization_type_id_fkey', 'nioktr', type_='foreignkey')
    op.create_foreign_key(None, 'nioktr', 'nioktr_types', ['type_id'], ['id'])
    op.drop_column('nioktr', 'organization_type_id')
    op.add_column('nioktr_budget', sa.Column('nioktr_budget_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'nioktr_budget', 'budget_type', ['nioktr_budget_id'], ['id'])
    op.add_column('nioktr_critical_tech', sa.Column('nioktr_critical_technologies_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'nioktr_critical_tech', 'nioktr', ['nioktr_critical_technologies_id'], ['id'])
    op.add_column('nioktr_priority_directions', sa.Column('nioktr_priority_derictions_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'nioktr_priority_directions', 'nioktr', ['nioktr_priority_derictions_id'], ['id'])
    op.add_column('organization', sa.Column('organization_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'organization', 'organization_type', ['organization_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organization', type_='foreignkey')
    op.drop_column('organization', 'organization_type_id')
    op.drop_constraint(None, 'nioktr_priority_directions', type_='foreignkey')
    op.drop_column('nioktr_priority_directions', 'nioktr_priority_derictions_id')
    op.drop_constraint(None, 'nioktr_critical_tech', type_='foreignkey')
    op.drop_column('nioktr_critical_tech', 'nioktr_critical_technologies_id')
    op.drop_constraint(None, 'nioktr_budget', type_='foreignkey')
    op.drop_column('nioktr_budget', 'nioktr_budget_id')
    op.add_column('nioktr', sa.Column('organization_type_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'nioktr', type_='foreignkey')
    op.create_foreign_key('nioktr_organization_type_id_fkey', 'nioktr', 'organization_type', ['organization_type_id'], ['id'])
    op.drop_column('nioktr', 'type_id')
    # ### end Alembic commands ###
