"""add nioktr2

Revision ID: ff9b28ef9c3d
Revises: 7fe1e6e8af80
Create Date: 2023-09-18 11:20:37.557117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff9b28ef9c3d'
down_revision: Union[str, None] = '7fe1e6e8af80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nioktr', sa.Column('type_id', sa.Integer(), nullable=False))
    op.drop_constraint('nioktr_organization_type_id_fkey', 'nioktr', type_='foreignkey')
    op.create_foreign_key(None, 'nioktr', 'source_type', ['type_id'], ['id'])
    op.drop_column('nioktr', 'organization_type_id')
    op.add_column('organization', sa.Column('organization_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'organization', 'organization_type', ['organization_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organization', type_='foreignkey')
    op.drop_column('organization', 'organization_type_id')
    op.add_column('nioktr', sa.Column('organization_type_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'nioktr', type_='foreignkey')
    op.create_foreign_key('nioktr_organization_type_id_fkey', 'nioktr', 'organization_type', ['organization_type_id'], ['id'])
    op.drop_column('nioktr', 'type_id')
    # ### end Alembic commands ###
